### ISSUE TITLE
Linking to wallet-core fails since 2.6.31 on Ubuntu 18.04

### ISSUE THREAD

**Issue by gituser** [trustwallet/wallet-core#1838]
**Describe the bug**
Commit https://github.com/trustwallet/wallet-core/commit/33ed1ac4f01364bd326042df33702418ab35cd42 broke linking on Ubuntu Bionic 18.04. 

Even though wallet-core builds fine with that commit, but linking is no longer working against wallet-core library.

I can no longer build my go application against wallet-core, I get linker errors.

If I revert this commit linking with my go app starts working again.

**To Reproduce**
Link your application and try to build it with `clang-10` on Ubuntu 18.04.

Here is how I build mine to get a static binary:

```
CC="clang-10 -fPIC -fPIE -fstack-protector-all" CXX="clang++-10" -fPIC -fPIE -fstack-protector-all -stdlib=libc++" CGO_CFLAGS="-I/home/build/trustwallet/test/../current/include" CGO_ENABLED=1 CGO_LDFLAGS="-L/home/build/trustwallet/test/../current/build -L/home/build/trustwallet/test/../current/build/trezor-crypto -lTrustWalletCore -lprotobuf -lTrezorCrypto -l:libc++.a -l:libc++abi.a -lm" go build -ldflags '-linkmode external -extldflags "-static-libgcc -static-libstdc++"' -a main.go
```

**Expected behavior**
wallet-core should be working in Ubuntu 18.04 as it did before with clang-10.

**Additional context**

Here is an error log from linking with that commit:
```
CC=""clang-10" -fPIC -fPIE -fstack-protector-all" CXX=""clang++-10" -fPIC -fPIE -fstack-protector-all -stdlib=libc++" CGO_CFLAGS="-I/home/build/trustwallet/test/../current/include" CGO_ENABLED=1 CGO_LDFLAGS="-L/home/build/trustwallet/test/../current/build -L/home/build/trustwallet/test/../current/build/trezor-crypto -lTrustWalletCore -lprotobuf -lTrezorCrypto -l:libc++.a -l:libc++abi.a -lm" go build -ldflags '-linkmode external -extldflags "-static-libgcc -static-libstdc++"' -a main.go
# _/home/build/trustwallet/test/config
/home/build/trustwallet/test/../current/build/libTrustWalletCore.a(Entry.cpp.o): In function `__cxx_global_var_init':
/usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/iostream:74: undefined reference to `std::ios_base::Init::Init()'
/usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/iostream:74: undefined reference to `std::ios_base::Init::~Init()'
/home/build/trustwallet/test/../current/build/libTrustWalletCore.a(Entry.cpp.o): In function `TW::Cosmos::Address::isValid(TWCoinType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/build/trustwallet/wallet-core/src/Cosmos/Address.h:40: undefined reference to `std::allocator<char>::allocator()'
/home/build/trustwallet/wallet-core/src/Cosmos/Address.h:40: undefined reference to `std::allocator<char>::~allocator()'
/home/build/trustwallet/wallet-core/src/Cosmos/Address.h:40: undefined reference to `std::allocator<char>::~allocator()'
/home/build/trustwallet/test/../current/build/libTrustWalletCore.a(Entry.cpp.o): In function `Address':
/home/build/trustwallet/wallet-core/src/Cosmos/Address.h:32: undefined reference to `std::allocator<char>::allocator()'
/home/build/trustwallet/wallet-core/src/Cosmos/Address.h:32: undefined reference to `std::allocator<char>::~allocator()'
/home/build/trustwallet/wallet-core/src/Cosmos/Address.h:32: undefined reference to `std::allocator<char>::~allocator()'
/home/build/trustwallet/test/../current/build/libTrustWalletCore.a(Signer.cpp.o): In function `__cxx_global_var_init':
/usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/iostream:74: undefined reference to `std::ios_base::Init::Init()'
/usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/iostream:74: undefined reference to `std::ios_base::Init::~Init()'
/home/build/trustwallet/test/../current/build/libTrustWalletCore.a(Signer.cpp.o): In function `TW::Cosmos::Proto::SigningOutput::set_signature(void const*, unsigned long)':
/home/build/trustwallet/wallet-core/src/Cosmos/../proto/Cosmos.pb.h:4721: undefined reference to `std::allocator<char>::allocator()'
/home/build/trustwallet/wallet-core/src/Cosmos/../proto/Cosmos.pb.h:4721: undefined reference to `std::allocator<char>::~allocator()'
/home/build/trustwallet/wallet-core/src/Cosmos/../proto/Cosmos.pb.h:4721: undefined reference to `std::allocator<char>::~allocator()'
/home/build/trustwallet/test/../current/build/libTrustWalletCore.a(Signer.cpp.o): In function `TW::Cosmos::Proto::SigningInput::set_private_key(void const*, unsigned long)':
/home/build/trustwallet/wallet-core/src/Cosmos/../proto/Cosmos.pb.h:4597: undefined reference to `std::allocator<char>::allocator()'
/home/build/trustwallet/wallet-core/src/Cosmos/../proto/Cosmos.pb.h:4597: undefined reference to `std::allocator<char>::~allocator()'
/home/build/trustwallet/wallet-core/src/Cosmos/../proto/Cosmos.pb.h:4597: undefined reference to `std::allocator<char>::~allocator()'
/home/build/trustwallet/test/../current/build/libTrustWalletCore.a(Signer.cpp.o): In function `std::vector<nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, std::allocator<nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > > >::reserve(unsigned long)':
/usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/vector.tcc:70: undefined reference to `std::__throw_length_error(char const*)'
/home/build/trustwallet/test/../current/build/libTrustWalletCore.a(Signer.cpp.o): In function `std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > > >::operator++()':
/usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_tree.h:287: undefined reference to `std::_Rb_tree_increment(std::_Rb_tree_node_base*)'
/home/build/trustwallet/test/../current/build/libTrustWalletCore.a(Signer.cpp.o): In function `std::vector<nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, std::allocator<nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > > >::_M_check_len(unsigned long, char const*) const':
/usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_vector.h:1643: undefined reference to `std::__throw_length_error(char const*)'
/home/build/trustwallet/test/../current/build/libTrustWalletCore.a(Signer.cpp.o): In function `serializer':
/home/build/trustwallet/wallet-core/build/local/include/nlohmann/detail/output/serializer.hpp:63: undefined reference to `std::allocator<char>::allocator()'
/home/build/trustwallet/wallet-core/build/local/include/nlohmann/detail/output/serializer.hpp:63: undefined reference to `std::allocator<char>::~allocator()'
/home/build/trustwallet/wallet-core/build/local/include/nlohmann/detail/output/serializer.hpp:63: undefined reference to `std::allocator<char>::~allocator()'
/home/build/trustwallet/test/../current/build/libTrustWalletCore.a(Signer.cpp.o): In function `nlohmann::detail::serializer<nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > >::dump_escaped(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
.....
```

Error log is very very long I could post it whole if you want.

**Comment by catenocrypt** [comment]
Thanks for reporting, I will investigate.
I don't remember the reason for removing '-stdlib=libc++'.
However, accidentally this was also removed from the sample app makefile recently, to fix linking of sample app (#1831).

**Comment by gituser** [comment]
@catenocrypt thank you for the quick reply.

I think it has something to do with new clang-11 support, though clang-10 should still be working.
I already use clang for compilation but it doesn't work until I revert this single commit.
Ubuntu 18.04 is LTS and imo should be still supported as its not EOL until April 2023.

**Comment by hewigovens** [comment]
@catenocrypt do we still have this issue?

**Comment by catenocrypt** [comment]
I have yet to test it in a true Ubuntu 18 environment.

**Comment by gituser** [comment]
@hewigovens the issue is still there unless someone reverted https://github.com/trustwallet/wallet-core/commit/33ed1ac4f01364bd326042df33702418ab35cd42

**Comment by catenocrypt** [comment]
Tried building on Ubuntu 18.04, and it worked fine.

OS: Ubuntu 18.04.6 (aws VM)
Environment: packages as installed as in  https://github.com/trustwallet/wallet-core/blob/master/.github/workflows/linux-ci.yml, except v10 instead of 11 for clang, llvm, plus few additional packages (cmake, unzip, ruby)
Version: latest master (commit `ff8296e4258d94545df769f7167aa553f2f13589`)
Built using ./bootstrap.sh
No errors, compiled lib, tester, unit tests executed fine.

Closing issue.

**Comment by gituser** [comment]
@catenocrypt did you build application against trust wallet? as trustwallet building wasn't affected, only apps relying on it.

**Comment by gituser** [comment]
@catnocrypt I've tested again on latest master `ff8296e4258d94545df769f7167aa553f2f13589` it doesn't work for me giving me similar errors when I'm trying to build my go app based on trustwallet.

If I try older version without https://github.com/trustwallet/wallet-core/commit/33ed1ac4f01364bd326042df33702418ab35cd42 it builds just fine.

**Comment by gituser** [comment]
@hewigovens yes go sample build fine, but it's a dynamic binary not static.

Static build fails with the new version I no longer can get a static binary for my go application, dynamic build works though.

**Comment by gituser** [comment]
I've tried some more it seems due these changes I have to change my LDFLAGS to this:

```diff
-	CC="$(CLANG) -fPIC -fPIE -fstack-protector-all" CXX="$(CLANGXX) -fPIC -fPIE -fstack-protector-all -stdlib=libc++" CGO_CFLAGS="-I$(WALLET_CORE_INCLUDE_PATH)" CGO_ENABLED=1 CGO_LDFLAGS="-L$(WALLET_CORE_LIBRARY_PATH) -L$(WALLET_CORE_LIBRARY_PATH)/trezor-crypto -lTrustWalletCore -lprotobuf -lTrezorCrypto -l:libc++.a -l:libc++abi.a -lm" go build -tags netgo -ldflags '-linkmode external -extldflags "-static -static-libgcc -static-libstdc++"' -a main.go
+	CC="$(CLANG) -fPIC -fPIE -fstack-protector-all" CXX="$(CLANGXX) -fPIC -fPIE -fstack-protector-all -stdlib=lstdc++" CGO_CFLAGS="-I$(WALLET_CORE_INCLUDE_PATH)" CGO_ENABLED=1 CGO_LDFLAGS="-L$(WALLET_CORE_LIBRARY_PATH) -L$(WALLET_CORE_LIBRARY_PATH)/trezor-crypto -lTrustWalletCore -lprotobuf -lTrezorCrypto -lstdc++ -lm" go build -tags netgo -ldflags '-linkmode external -extldflags "-static -static-libgcc -static-libstdc++"' -a main.go
```
and then it builds my go app statically.

**Comment by hewigovens** [comment]
@gituser good to know it worked for you, wallet core can be built and linked to lstdc++ by default with clang 11, libc++ usually is not installed

have you tried to update libc++ somehow?

**Comment by gituser** [comment]
@hewigovens 

I have:
```
$ dpkg -l|grep libc++
ii  libc++-10-dev:amd64                   1:10.0.0-4ubuntu1~18.04.2            amd64        LLVM C++ Standard library (development files)
ii  libc++1-10:amd64                      1:10.0.0-4ubuntu1~18.04.2            amd64        LLVM C++ Standard library
ii  libc++abi-10-dev:amd64                1:10.0.0-4ubuntu1~18.04.2            amd64        LLVM low level support for a standard C++ library (development files)
ii  libc++abi1-10:amd64                   1:10.0.0-4ubuntu1~18.04.2            amd64        LLVM low level support for a standard C++ library
```
I'm using clang-10 for now as clang-11 isn't available for 18.04, before the mentioned commit it worked just fine with the LDFLAGS I've used with `libc++` instead of `lstdc++`

**Comment by hewigovens** [comment]
Thanks for the info, right now it should just work with `lstdc++` on both clang 10 and clang 11
